(() => {
  const API = 'api/index.php';
  const tokenKey = 'leni-jogos-token';
  const page = location.pathname.split('/').pop() || 'index.html';
  const gameByPage = {'lava.html':'fogo-agua','tower-defense.html':'guardioes-trilha','snake.html':'cobrinha','tile-game.html':'mesa-sequencias','worms.html':'worms'};
  const game = gameByPage[page];
  const startedAt = Date.now();
  const token = () => localStorage.getItem(tokenKey) || '';
  async function request(action, options={}) { const response = await fetch(`${API}?action=${action}`, { ...options, headers: {'Content-Type':'application/json', ...(token()?{Authorization:`Bearer ${token()}`}:{}) , ...(options.headers||{})} }); const data=await response.json().catch(()=>({error:'Servidor indisponível.'})); if(!response.ok) throw new Error(data.error||'Não foi possível concluir.'); return data; }
  async function event(type,payload={}) { if(!game||!token()) return; try { await request('event',{method:'POST',body:JSON.stringify({game,type,seconds:Math.round((Date.now()-startedAt)/1000),payload})}); } catch {} }
  function authModal() { const wrapper=document.createElement('div'); wrapper.className='auth-overlay'; wrapper.innerHTML=`<section class="auth-card"><p class="eyebrow">Conta Leni Jogos</p><h2>Entre para jogar</h2><p>Seu progresso, tempo de jogo e estatísticas ficam salvos na sua conta.</p><div class="auth-tabs"><button data-tab="login" class="active">Entrar</button><button data-tab="register">Cadastrar</button></div><form id="authForm"><label class="register-only" hidden>Apelido<input name="nickname" autocomplete="nickname" maxlength="30"></label><label>Celular<input name="phone" inputmode="tel" autocomplete="tel" required></label><label>Senha<input name="password" type="password" autocomplete="current-password" minlength="8" required></label><button type="submit">Continuar</button><small id="authError"></small></form></section>`; document.body.append(wrapper); let mode='login'; const form=wrapper.querySelector('form'), error=wrapper.querySelector('#authError'); wrapper.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{mode=button.dataset.tab;wrapper.querySelectorAll('[data-tab]').forEach(tab=>tab.classList.toggle('active',tab===button));wrapper.querySelector('.register-only').hidden=mode!=='register';form.password.autocomplete=mode==='register'?'new-password':'current-password';error.textContent=''}); form.onsubmit=async e=>{e.preventDefault();error.textContent='';const body=Object.fromEntries(new FormData(form));try{const data=await request(mode,{method:'POST',body:JSON.stringify(body)});localStorage.setItem(tokenKey,data.token);location.reload()}catch(err){error.textContent=err.message}}; }
  async function boot() { try { const data=await request('me'); document.documentElement.classList.add('authenticated'); const badge=document.createElement('div');badge.className='account-badge';badge.innerHTML=`<span>👤 ${data.user.nickname}</span><button>Sair</button>`;badge.querySelector('button').onclick=async()=>{try{await request('logout',{method:'POST'})}catch{}localStorage.removeItem(tokenKey);location.href='index.html'};document.body.append(badge);if(game)event('open'); } catch { localStorage.removeItem(tokenKey); if(page!=='index.html'&&page!=='') location.href='index.html'; else authModal(); } }
  addEventListener('pagehide',()=>{if(game&&token())fetch(`${API}?action=event`,{method:'POST',keepalive:true,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`},body:JSON.stringify({game,type:'close',seconds:Math.round((Date.now()-startedAt)/1000)})}).catch(()=>{})});
  async function saveProgress(game,progress){if(!token())return;try{await request('progress',{method:'POST',body:JSON.stringify({game,progress})})}catch{}}
  async function loadProgress(game){if(!token())return {};try{return (await request(`progress&game=${encodeURIComponent(game)}`)).progress||{}}catch{return {}}}
  window.LeniJogos={request,event,token,saveProgress,loadProgress}; boot();
})();
