const colors = ['red','blue','yellow','black'];
const names = ['Você','Computador Azul','Computador Dourado','Computador Roxo'];
const rackEl=document.querySelector('#rack'), meldsEl=document.querySelector('#melds'), opponentsEl=document.querySelector('#opponents');
const messageEl=document.querySelector('#tileMessage'),turnEl=document.querySelector('#turnLabel'),pileEl=document.querySelector('#pileCount'),rackCountEl=document.querySelector('#rackCount');
const setupModal=document.querySelector('#setupModal'),setupForm=document.querySelector('#setupForm'),playBtn=document.querySelector('#playTiles'),drawBtn=document.querySelector('#drawTile');
let pile=[],players=[],melds=[],turn=0,difficulty='normal',selected=new Set(),finished=false,busy=false;
function shuffle(items){for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}return items}
function createPile(){let id=0;return shuffle(colors.flatMap(color=>Array.from({length:2},()=>Array.from({length:13},(_,i)=>({id:id++,color,number:i+1})))).flat())}
function sortRack(rack){rack.sort((a,b)=>colors.indexOf(a.color)-colors.indexOf(b.color)||a.number-b.number)}
function startGame(count,level){pile=createPile();players=Array.from({length:count},(_,i)=>({name:names[i],rack:[]}));melds=[];difficulty=level;turn=0;finished=false;busy=false;selected.clear();for(let r=0;r<14;r++)players.forEach(player=>player.rack.push(pile.pop()));players.forEach(player=>sortRack(player.rack));setupModal.hidden=true;setMessage('Sua vez! Monte uma sequência ou um grupo com pelo menos três peças.');render()}
function setMessage(text){messageEl.textContent=text}
function validate(tiles){if(tiles.length<3)return false;const sorted=[...tiles].sort((a,b)=>a.number-b.number);const group=tiles.every(tile=>tile.number===tiles[0].number)&&new Set(tiles.map(tile=>tile.color)).size===tiles.length;const run=tiles.every(tile=>tile.color===tiles[0].color)&&sorted.every((tile,i)=>i===0||tile.number===sorted[i-1].number+1);return group||run}
function findMeld(rack, smart=true){for(let number=1;number<=13;number++){const group=colors.map(color=>rack.find(tile=>tile.number===number&&tile.color===color)).filter(Boolean);if(group.length>=3)return group.slice(0,smart?4:3)}for(const color of colors){const list=rack.filter(tile=>tile.color===color).sort((a,b)=>a.number-b.number);for(let i=0;i<list.length;i++){const run=[list[i]];for(let j=i+1;j<list.length;j++){if(list[j].number===run.at(-1).number+1)run.push(list[j]);else if(list[j].number>run.at(-1).number+1)break}if(run.length>=3)return run.slice(0,smart?run.length:3)}}return null}
function removeTiles(rack,tiles){tiles.forEach(tile=>rack.splice(rack.findIndex(item=>item.id===tile.id),1))}
function drawOne(player){if(pile.length)player.rack.push(pile.pop());sortRack(player.rack)}
function checkWinner(player){if(player.rack.length)return false;window.LeniJogos?.event(player===players[0]?'win':'loss');finished=true;busy=false;turnEl.textContent=player===players[0]?'Você venceu!':'Os computadores venceram';setMessage(player===players[0]?'Parabéns! Você esvaziou seu suporte primeiro.':'Fim de partida. Tente novamente com uma nova estratégia.');render();return true}
function nextTurn(){if(finished)return;turn=(turn+1)%players.length;render();if(turn===0){busy=false;setMessage('Sua vez! Escolha peças ou compre uma nova.')}else{busy=true;setMessage(`${players[turn].name} está pensando...`);setTimeout(botTurn,difficulty==='hard'?430:700)}}
function botTurn(){if(finished)return;const bot=players[turn],chance={easy:.58,normal:.82,hard:1}[difficulty];const combo=Math.random()<=chance?findMeld(bot.rack,difficulty!=='easy'):null;if(combo){removeTiles(bot.rack,combo);melds.push({owner:bot.name,tiles:combo});setMessage(`${bot.name} baixou ${combo.length} peças.`);if(checkWinner(bot))return}else{drawOne(bot);setMessage(`${bot.name} comprou uma peça.`)}render();setTimeout(nextTurn,500)}
function renderTile(tile,clickable=false){const button=document.createElement(clickable?'button':'i');button.className=`game-tile ${tile.color}${selected.has(tile.id)?' selected':''}`;button.textContent=tile.number;if(clickable)button.addEventListener('click',()=>{if(busy||finished)return;selected.has(tile.id)?selected.delete(tile.id):selected.add(tile.id);render()});return button}
function render(){pileEl.textContent=pile.length;rackCountEl.textContent=`${players[0]?.rack.length||0} peças`;rackEl.innerHTML='';(players[0]?.rack||[]).forEach(tile=>rackEl.append(renderTile(tile,true)));opponentsEl.innerHTML='';players.slice(1).forEach((player,index)=>{const card=document.createElement('div');card.className=`opponent ${turn===index+1?'active':''}`;card.innerHTML=`<span>🤖 ${player.name}</span><small>${player.rack.length} peças</small>`;opponentsEl.append(card)});meldsEl.innerHTML='';if(!melds.length)meldsEl.innerHTML='<p class="empty-table">As combinações aparecerão aqui.</p>';melds.forEach(meld=>{const group=document.createElement('div');group.className='meld';group.title=`Baixado por ${meld.owner}`;meld.tiles.forEach(tile=>group.append(renderTile(tile)));meldsEl.append(group)});turnEl.textContent=finished?turnEl.textContent:(turn===0?'Sua vez':`Vez de ${players[turn]?.name}`);playBtn.disabled=busy||finished;drawBtn.disabled=busy||finished}
playBtn.addEventListener('click',()=>{if(busy||finished)return;const tiles=players[0].rack.filter(tile=>selected.has(tile.id));if(!validate(tiles))return setMessage('Combinação inválida. Use 3+ números seguidos da mesma cor ou o mesmo número em cores diferentes.');removeTiles(players[0].rack,tiles);melds.push({owner:'Você',tiles});selected.clear();setMessage('Boa jogada! Combinação adicionada à mesa.');render();if(!checkWinner(players[0]))setTimeout(nextTurn,450)});
drawBtn.addEventListener('click',()=>{if(busy||finished)return;drawOne(players[0]);selected.clear();setMessage('Você comprou uma peça e passou a vez.');render();setTimeout(nextTurn,450)});
setupForm.addEventListener('submit',event=>{event.preventDefault();startGame(Number(document.querySelector('#playerCount').value),document.querySelector('#difficulty').value)});
document.querySelector('#newTileGame').addEventListener('click',()=>{setupModal.hidden=false});
render();
