const canvas=document.querySelector('#wormsGame'),ctx=canvas.getContext('2d');
const stage=document.querySelector('#wormsStage'),messageEl=document.querySelector('#wormsMessage');
const hud={team:document.querySelector('#teamLabel'),worm:document.querySelector('#wormLabel'),health:document.querySelector('#healthLabel'),angle:document.querySelector('#angleLabel'),power:document.querySelector('#powerLabel'),wind:document.querySelector('#windLabel')};
const terrain=document.createElement('canvas'),terrainCtx=terrain.getContext('2d',{willReadFrequently:true});terrain.width=canvas.width;terrain.height=canvas.height;
const GRAVITY=.2,WORM_RADIUS=14,BLAST_RADIUS=72,teams=[{name:'Coral',color:'#ff766c'},{name:'Azul',color:'#62baff'}];
let worms=[],teamIndex=0,wormCursors=[0,0],projectile=null,particles=[],keys=new Set(),charging=false,power=0,wind=0,turnLocked=false,gameOver=false,audio,terrainProfile=[];
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value)),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function tone(freq=440,duration=.08,type='sine',volume=.05){try{audio??=new AudioContext();const osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(volume,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration)}catch{}}
function terrainAt(x,y){if(x<0||x>=terrain.width||y<0||y>=terrain.height)return y>=terrain.height;return terrainCtx.getImageData(Math.floor(x),Math.floor(y),1,1).data[3]>10}
function surfaceY(x){x=clamp(Math.round(x),0,terrain.width-1);for(let y=100;y<terrain.height;y++)if(terrainAt(x,y))return y;return terrain.height}
function generateTerrain(){terrainCtx.clearRect(0,0,terrain.width,terrain.height);terrainProfile=[];let y=410;for(let x=0;x<=terrain.width;x+=12){y+=Math.sin(x/67)*3+(Math.random()-.5)*16;y=clamp(y,300,535);terrainProfile.push({x,y})}terrainCtx.fillStyle='#55733e';terrainCtx.beginPath();terrainCtx.moveTo(0,terrain.height);terrainProfile.forEach(point=>terrainCtx.lineTo(point.x,point.y));terrainCtx.lineTo(terrain.width,terrain.height);terrainCtx.closePath();terrainCtx.fill();terrainCtx.globalCompositeOperation='source-atop';const gradient=terrainCtx.createLinearGradient(0,280,0,700);gradient.addColorStop(0,'#8ebc55');gradient.addColorStop(.09,'#62883e');gradient.addColorStop(1,'#352c2b');terrainCtx.fillStyle=gradient;terrainCtx.fillRect(0,0,terrain.width,terrain.height);terrainCtx.globalCompositeOperation='source-over'}
function createWorm(team,name,x){return{team,name,x,y:surfaceY(x)-WORM_RADIUS,vx:0,vy:0,health:100,angle:45,facing:team===0?1:-1,alive:true,phase:Math.random()*6}}
function resetGame(){generateTerrain();worms=[createWorm(0,'Luma',130),createWorm(0,'Nino',330),createWorm(0,'Bia',520),createWorm(1,'Zeca',700),createWorm(1,'Mila',910),createWorm(1,'Téo',1080)];teamIndex=0;wormCursors=[0,0];projectile=null;particles=[];keys.clear();charging=false;power=0;turnLocked=false;gameOver=false;wind=randomWind();messageEl.textContent='Time Coral: mova Luma e prepare o disparo.';updateHud()}
function randomWind(){return Math.round((Math.random()*2-1)*18)/10}
function currentWorm(){const alive=worms.filter(worm=>worm.alive&&worm.team===teamIndex);return alive[wormCursors[teamIndex]%alive.length]}
function updateHud(){const worm=currentWorm();hud.team.textContent=teams[teamIndex].name;hud.team.style.color=teams[teamIndex].color;hud.worm.textContent=worm?.name||'—';hud.health.textContent=worm?.health??0;hud.angle.textContent=`${worm?.angle??0}°`;hud.power.textContent=`${Math.round(power)}%`;hud.wind.textContent=`${wind>0?'→':wind<0?'←':'•'} ${Math.abs(wind).toFixed(1)}`}
function nextTurn(){if(gameOver)return;const winner=teams.find((_,index)=>worms.some(worm=>worm.alive&&worm.team===index)&&!worms.some(worm=>worm.alive&&worm.team!==index));if(winner){gameOver=true;turnLocked=true;messageEl.textContent=`🏆 Time ${winner.name} venceu a batalha!`;return}wormCursors[teamIndex]++;teamIndex=teamIndex?0:1;const alive=worms.filter(worm=>worm.alive&&worm.team===teamIndex);wormCursors[teamIndex]%=alive.length;wind=randomWind();power=0;charging=false;turnLocked=false;messageEl.textContent=`Time ${teams[teamIndex].name}: vez de ${currentWorm().name}.`;updateHud()}
function skipTurn(){if(turnLocked||projectile||gameOver)return;turnLocked=true;messageEl.textContent='Turno pulado.';setTimeout(nextTurn,550)}
function shoot(){if(!charging||turnLocked||gameOver)return;charging=false;turnLocked=true;const worm=currentWorm(),force=5+power*.115,angle=worm.angle*Math.PI/180;projectile={x:worm.x+worm.facing*20,y:worm.y-8,vx:Math.cos(angle)*force*worm.facing,vy:-Math.sin(angle)*force,trail:[]};tone(230,.13,'square',.07);messageEl.textContent=`${worm.name} disparou!`;power=0;updateHud()}
function explode(x,y){tone(85,.28,'sawtooth',.1);terrainCtx.save();terrainCtx.globalCompositeOperation='destination-out';terrainCtx.beginPath();terrainCtx.arc(x,y,BLAST_RADIUS,0,Math.PI*2);terrainCtx.fill();terrainCtx.restore();for(const worm of worms){if(!worm.alive)continue;const dist=distance(worm,{x,y});if(dist<BLAST_RADIUS+WORM_RADIUS){const damage=Math.round((1-dist/(BLAST_RADIUS+WORM_RADIUS))*68);worm.health=Math.max(0,worm.health-damage);worm.vx+=(worm.x-x)/Math.max(dist,1)*4;worm.vy=-4;if(!worm.health)worm.alive=false}}for(let i=0;i<58;i++){const angle=Math.random()*Math.PI*2,speed=1+Math.random()*5;particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed-1,life:28+Math.random()*28,size:2+Math.random()*5,color:i%3?'#ffb357':'#6a4934'})}projectile=null;setTimeout(nextTurn,1300)}
function updateWorms(){for(const worm of worms){if(!worm.alive)continue;worm.phase+=.05;const grounded=terrainAt(worm.x,worm.y+WORM_RADIUS+2);if(!grounded){worm.vy+=GRAVITY;worm.y+=worm.vy;worm.x+=worm.vx;worm.vx*=.93}else{worm.vy=0;worm.vx*=.72;worm.y=surfaceY(worm.x)-WORM_RADIUS}if(worm.y>canvas.height+30){worm.health=0;worm.alive=false}}}
function updateControls(){if(turnLocked||projectile||gameOver)return;const worm=currentWorm();if(!worm)return;let dx=0;if(keys.has('KeyA'))dx=-1.35;if(keys.has('KeyD'))dx=1.35;if(dx){worm.x=clamp(worm.x+dx,16,canvas.width-16);worm.facing=Math.sign(dx);worm.y=Math.min(worm.y,surfaceY(worm.x)-WORM_RADIUS)}if(keys.has('ArrowUp'))worm.angle=clamp(worm.angle+.55,5,85);if(keys.has('ArrowDown'))worm.angle=clamp(worm.angle-.55,5,85);if(charging)power=clamp(power+1.05,0,100);updateHud()}
function updateProjectile(){if(!projectile)return;projectile.trail.push({x:projectile.x,y:projectile.y,life:20});projectile.trail.forEach(dot=>dot.life--);projectile.trail=projectile.trail.filter(dot=>dot.life>0);projectile.vx+=wind*.005;projectile.vy+=GRAVITY;projectile.x+=projectile.vx;projectile.y+=projectile.vy;const hitWorm=worms.find(worm=>worm.alive&&distance(worm,projectile)<WORM_RADIUS+5);if(hitWorm||terrainAt(projectile.x,projectile.y)||projectile.x<0||projectile.x>canvas.width||projectile.y>canvas.height)explode(clamp(projectile.x,0,canvas.width),clamp(projectile.y,0,canvas.height))}
function updateParticles(){for(const item of particles){item.x+=item.vx;item.y+=item.vy;item.vy+=.12;item.life--}particles=particles.filter(item=>item.life>0)}
function update(){updateControls();updateWorms();updateProjectile();updateParticles()}
function drawBackground(){const sky=ctx.createLinearGradient(0,0,0,700);sky.addColorStop(0,'#55b7eb');sky.addColorStop(.62,'#b7e6e9');sky.addColorStop(1,'#f8d48b');ctx.fillStyle=sky;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='rgba(255,246,188,.75)';ctx.beginPath();ctx.arc(1030,100,52,0,Math.PI*2);ctx.fill();drawMountains('#6ca7a4',340,95,.55);drawMountains('#4d817a',390,130,.8)}
function drawMountains(color,base,height,offset){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,base);for(let x=0;x<=canvas.width;x+=80)ctx.lineTo(x,base-height*(.35+.65*Math.abs(Math.sin(x*.008+offset))));ctx.lineTo(canvas.width,base);ctx.closePath();ctx.fill()}
function drawTerrain(){ctx.drawImage(terrain,0,0);ctx.strokeStyle='rgba(212,244,125,.65)';ctx.lineWidth=4;ctx.beginPath();for(let x=0;x<canvas.width;x+=8){const y=surfaceY(x);x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}
function drawWorms(){for(const worm of worms){if(!worm.alive)continue;const active=worm===currentWorm()&&!turnLocked,bob=Math.sin(worm.phase)*1.5;ctx.fillStyle=teams[worm.team].color;ctx.strokeStyle=active?'#fff59b':'rgba(255,255,255,.72)';ctx.lineWidth=active?4:2;ctx.beginPath();ctx.ellipse(worm.x,worm.y+bob,13,17,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(worm.x-5,worm.y+bob-4,3,0,Math.PI*2);ctx.arc(worm.x+5,worm.y+bob-4,3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#243341';ctx.beginPath();ctx.arc(worm.x-4,worm.y+bob-4,1.4,0,Math.PI*2);ctx.arc(worm.x+6,worm.y+bob-4,1.4,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(5,18,28,.78)';ctx.fillRect(worm.x-18,worm.y-32,36,5);ctx.fillStyle=worm.health>45?'#70ed87':'#ff6962';ctx.fillRect(worm.x-18,worm.y-32,36*worm.health/100,5);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 11px sans-serif';ctx.fillText(worm.name,worm.x,worm.y-39);if(active){const angle=worm.angle*Math.PI/180;ctx.strokeStyle='#fff59b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(worm.x,worm.y-7);ctx.lineTo(worm.x+Math.cos(angle)*worm.facing*48,worm.y-7-Math.sin(angle)*48);ctx.stroke()}}}
function drawProjectile(){if(!projectile)return;for(const dot of projectile.trail){ctx.globalAlpha=dot.life/20;ctx.fillStyle='#fff1a8';ctx.beginPath();ctx.arc(dot.x,dot.y,3,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle='#303743';ctx.beginPath();ctx.arc(projectile.x,projectile.y,6,0,Math.PI*2);ctx.fill()}
function drawParticles(){for(const item of particles){ctx.globalAlpha=Math.min(1,item.life/20);ctx.fillStyle=item.color;ctx.beginPath();ctx.arc(item.x,item.y,item.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function draw(){drawBackground();drawTerrain();drawWorms();drawProjectile();drawParticles()}
function loop(){update();draw();requestAnimationFrame(loop)}
window.addEventListener('keydown',event=>{if(['KeyA','KeyD','ArrowUp','ArrowDown','Space'].includes(event.code))event.preventDefault();keys.add(event.code);if(event.code==='Space'&&!event.repeat&&!turnLocked&&!projectile&&!gameOver)charging=true});
window.addEventListener('keyup',event=>{keys.delete(event.code);if(event.code==='Space')shoot()});
function touchControl(action,active){const codes={left:'KeyA',right:'KeyD','aim-up':'ArrowUp','aim-down':'ArrowDown'};if(codes[action])return active?keys.add(codes[action]):keys.delete(codes[action]);if(action==='fire'){if(active&&!turnLocked&&!projectile&&!gameOver)charging=true;else if(!active)shoot()}if(action==='skip'&&active)skipTurn()}
document.querySelectorAll('[data-worm-control]').forEach(button=>{const action=button.dataset.wormControl;button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture(event.pointerId);touchControl(action,true)});button.addEventListener('pointerup',()=>touchControl(action,false));button.addEventListener('pointercancel',()=>touchControl(action,false));button.addEventListener('pointerleave',()=>touchControl(action,false))});
document.querySelector('#restartWorms').addEventListener('click',resetGame);document.querySelector('#fullscreenWorms').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():stage.requestFullscreen());document.addEventListener('fullscreenchange',()=>{document.querySelector('#fullscreenWorms').textContent=document.fullscreenElement?'⛶ Sair':'⛶ Tela cheia'});
resetGame();requestAnimationFrame(loop);
