import { createServer } from 'node:http';
import { createHmac, timingSafeEqual, randomUUID } from 'node:crypto';
import { WebSocketServer } from 'ws';
const secret=process.env.JOGOS_WS_SECRET;if(!secret)throw new Error('JOGOS_WS_SECRET ausente');
const port=Number(process.env.JOGOS_WS_PORT||8081),waiting=[],rooms=new Map();
function verify(token){const [body,signature]=String(token||'').split('.');if(!body||!signature)return null;const expected=createHmac('sha256',secret).update(body).digest('hex');if(signature.length!==expected.length||!timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return null;const data=JSON.parse(Buffer.from(body,'base64').toString('utf8'));return data.exp*1000>Date.now()?data:null}
function send(ws,payload){if(ws.readyState===ws.OPEN)ws.send(JSON.stringify(payload))}
function leave(ws){const i=waiting.indexOf(ws);if(i>=0)waiting.splice(i,1);if(!ws.room)return;const room=rooms.get(ws.room);rooms.delete(ws.room);room?.players.forEach(player=>{if(player!==ws){player.room=null;send(player,{type:'opponent-left'})}})}
const server=createServer((_,res)=>{res.writeHead(200);res.end('Leni Jogos realtime')});const wss=new WebSocketServer({server});
wss.on('connection',(ws,request)=>{const url=new URL(request.url,'http://localhost'),user=verify(url.searchParams.get('token'));if(!user)return ws.close(1008,'Token inválido');ws.user=user;send(ws,{type:'authenticated',nickname:user.nickname});ws.on('message',raw=>{let msg;try{msg=JSON.parse(raw)}catch{return}if(msg.type==='queue'){if(waiting.includes(ws)||ws.room)return;const opponent=waiting.shift();if(!opponent){waiting.push(ws);return send(ws,{type:'waiting'})}const id=randomUUID(),seed=Math.floor(Math.random()*2147483647),players=[opponent,ws];rooms.set(id,{players});players.forEach((player,team)=>{player.room=id;send(player,{type:'ready',room:id,team,seed,opponent:players[team?0:1].user.nickname})})}if(msg.type==='action'&&ws.room){const room=rooms.get(ws.room);room?.players.forEach(player=>{if(player!==ws)send(player,{type:'action',action:msg.action,active:!!msg.active})})}});ws.on('close',()=>leave(ws))});server.listen(port,()=>console.log(`Realtime em :${port}`));
